# -*- coding: utf-8 -*-
"""
Aggregate schema modules for each table.
"""

from .elo_history import (
    CREATE_ELO_HISTORY_TABLE,
    CREATE_INDEX_ELOHIST_DATE,
    CREATE_INDEX_ELOHIST_MATCH_ID,
    CREATE_INDEX_ELOHIST_PLAYER_ID,
    CREATE_SEQ_ELO_HISTORY,
)
from .matches import (
    CREATE_INDEX_MATCHES_LOSER_TEAM_ID,
    CREATE_INDEX_MATCHES_PLAYED_AT,
    CREATE_INDEX_MATCHES_WINNER_TEAM_ID,
    CREATE_MATCHES_TABLE,
    CREATE_SEQ_MATCHES,
)
from .periodic_rankings import (
    CREATE_INDEX_PERIODIC_RANKINGS_PERIOD,
    CREATE_INDEX_PERIODIC_RANKINGS_PLAYER_ID,
    CREATE_PERIODIC_RANKINGS_TABLE,
    CREATE_SEQ_PERIODIC_RANKINGS,
)
from .players import (
    CREATE_INDEX_PLAYERS_NAME,
    CREATE_PLAYERS_TABLE,
    CREATE_SEQ_PLAYERS,
)
from .team_periodic_rankings import (
    CREATE_INDEX_TEAM_PERIODIC_RANKINGS_PERIOD,
    CREATE_INDEX_TEAM_PERIODIC_RANKINGS_TEAM_ID,
    CREATE_SEQ_TEAM_PERIODIC_RANKINGS,
    CREATE_TEAM_PERIODIC_RANKINGS_TABLE,
)
from .teams import (
    CREATE_INDEX_TEAMS_PLAYER_PAIR_ORDER_INSENSITIVE,
    CREATE_SEQ_TEAMS,
    CREATE_TEAMS_TABLE,
)

__all__ = [
    # Players
    "CREATE_SEQ_PLAYERS",
    "CREATE_PLAYERS_TABLE",
    "CREATE_INDEX_PLAYERS_NAME",
    # Teams
    "CREATE_SEQ_TEAMS",
    "CREATE_TEAMS_TABLE",
    "CREATE_INDEX_TEAMS_PLAYER_PAIR_ORDER_INSENSITIVE",
    # Matches
    "CREATE_SEQ_MATCHES",
    "CREATE_MATCHES_TABLE",
    "CREATE_INDEX_MATCHES_WINNER_TEAM_ID",
    "CREATE_INDEX_MATCHES_LOSER_TEAM_ID",
    "CREATE_INDEX_MATCHES_PLAYED_AT",
    # ELO History
    "CREATE_SEQ_ELO_HISTORY",
    "CREATE_ELO_HISTORY_TABLE",
    "CREATE_INDEX_ELOHIST_PLAYER_ID",
    "CREATE_INDEX_ELOHIST_MATCH_ID",
    "CREATE_INDEX_ELOHIST_DATE",
    # Periodic Rankings
    "CREATE_SEQ_PERIODIC_RANKINGS",
    "CREATE_PERIODIC_RANKINGS_TABLE",
    "CREATE_INDEX_PERIODIC_RANKINGS_PLAYER_ID",
    "CREATE_INDEX_PERIODIC_RANKINGS_PERIOD",
    # Team Periodic Rankings
    "CREATE_SEQ_TEAM_PERIODIC_RANKINGS",
    "CREATE_TEAM_PERIODIC_RANKINGS_TABLE",
    "CREATE_INDEX_TEAM_PERIODIC_RANKINGS_TEAM_ID",
    "CREATE_INDEX_TEAM_PERIODIC_RANKINGS_PERIOD",
]
