# -*- coding: utf-8 -*-
"""
Aggregate schema modules for each table.
"""

from .elo_history import *
from .matches import *
from .periodic_rankings import *
from .players import *
from .team_periodic_rankings import *
from .teams import *

__all__ = [
    "CREATE_SEQ_PLAYERS",
    "CREATE_PLAYERS_TABLE",
    "CREATE_INDEX_PLAYERS_NAME",
    "CREATE_SEQ_TEAMS",
    "CREATE_TEAMS_TABLE",
    "CREATE_SEQ_MATCHES",
    "CREATE_MATCHES_TABLE",
    "CREATE_INDEX_MATCHES_TEAM1",
    "CREATE_INDEX_MATCHES_TEAM2",
    "CREATE_INDEX_MATCHES_WINNER",
    "CREATE_INDEX_MATCHES_DATE",
    "CREATE_SEQ_ELO_HISTORY",
    "CREATE_ELO_HISTORY_TABLE",
    "CREATE_INDEX_ELOHIST_PLAYER",
    "CREATE_INDEX_ELOHIST_MATCH",
    "CREATE_INDEX_ELOHIST_UPDATED",
    "CREATE_SEQ_PERIODIC_RANKINGS",
    "CREATE_PERIODIC_RANKINGS_TABLE",
    "CREATE_INDEX_PERIODIC_PLAYER",
    "CREATE_INDEX_PERIODIC_PERIOD_PLAYER",
    "CREATE_SEQ_TEAM_PERIODIC_RANKINGS",
    "CREATE_TEAM_PERIODIC_RANKINGS_TABLE",
]
